########################################################
# Simple App Deployment & Service & HPA
#######################################################
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  labels:
    app: simple-app-service
    groupId: simple-app
spec:
  selector:
    app.kubernetes.io/name: simple-app-deployment
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: simple-app-deployment
    groupId: simple-app
  name: simple-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-app-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-app-deployment
        groupId: simple-app
    spec:
      containers:
        - name: simple-app-container
          image: simple-app:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          resources:   # we are limiting resources for pods to make sure autoscaling works
            requests:
              cpu: 750m
              memory: 750m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-app-hpa
  labels:
    app.kubernetes.io/name: simple-app-hpa
    groupId: simple-app
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
